org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official

# JDK 21 (JBR) — AGP 8.5 / Gradle 8.7 nao rodam bem no JDK 25 da IDE.
# Ajuste se o caminho mudar.
org.gradle.java.home=C:\\Users\\Usuario\\.jdks\\jbr-21.0.11
